/**
 * CVEDIA-RT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: support@cvedia.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.1.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CoreGetSystemConfigV1_200_response.h
 *
 * 
 */

#ifndef CVEDIA_RT_REST_CLIENT_MODEL_CoreGetSystemConfigV1_200_response_H_
#define CVEDIA_RT_REST_CLIENT_MODEL_CoreGetSystemConfigV1_200_response_H_


#include "defines.h"
#include "rt_rest_client/ModelBase.h"

#include "rt_rest_client/model/SystemConfigEntity.h"
#include <vector>

namespace cvedia {
namespace rt {
namespace rest {
namespace client {
namespace model {

class SystemConfigEntity;

/// <summary>
/// 
/// </summary>
class EXPORT_CLASS  CoreGetSystemConfigV1_200_response
    : public ModelBase
{
public:
    EXPORT CoreGetSystemConfigV1_200_response();
    EXPORT virtual ~CoreGetSystemConfigV1_200_response();

    /////////////////////////////////////////////
    /// ModelBase overrides

    EXPORT void validate() override;

    EXPORT web::json::value toJson() const override;
    EXPORT bool fromJson(const web::json::value& json) override;

    EXPORT void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    EXPORT bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CoreGetSystemConfigV1_200_response members

    /// <summary>
    /// 
    /// </summary>
    EXPORT std::vector<std::shared_ptr<SystemConfigEntity>>& getSystemConfig();
    EXPORT bool systemConfigIsSet() const;
    EXPORT void unsetsystemConfig();

    EXPORT void setSystemConfig(const std::vector<std::shared_ptr<SystemConfigEntity>>& value);


protected:
    std::vector<std::shared_ptr<SystemConfigEntity>> m_systemConfig;
    bool m_systemConfigIsSet;
};


}
}
}
}
}

#endif /* CVEDIA_RT_REST_CLIENT_MODEL_CoreGetSystemConfigV1_200_response_H_ */
