/**
 * CVEDIA-RT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@cvedia.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * InstanceRead.h
 *
 * 
 */

#ifndef CVEDIA_RT_REST_CLIENT_MODEL_InstanceRead_H_
#define CVEDIA_RT_REST_CLIENT_MODEL_InstanceRead_H_


#include "defines.h"
#include "rt_rest_client/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace cvedia {
namespace rt {
namespace rest {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class EXPORT_CLASS  InstanceRead
    : public ModelBase
{
public:
    EXPORT InstanceRead();
    EXPORT virtual ~InstanceRead();

    /////////////////////////////////////////////
    /// ModelBase overrides

    EXPORT void validate() override;

    EXPORT web::json::value toJson() const override;
    EXPORT bool fromJson(const web::json::value& json) override;

    EXPORT void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    EXPORT bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// InstanceRead members

    /// <summary>
    /// 
    /// </summary>
    EXPORT utility::string_t getInstanceId() const;
    EXPORT bool instanceIdIsSet() const;
    EXPORT void unsetinstanceId();

    EXPORT void setInstanceId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    EXPORT utility::string_t getDisplayName() const;
    EXPORT bool displayNameIsSet() const;
    EXPORT void unsetdisplayName();

    EXPORT void setDisplayName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    EXPORT utility::string_t getGroup() const;
    EXPORT bool groupIsSet() const;
    EXPORT void unsetgroup();

    EXPORT void setGroup(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    EXPORT utility::string_t getSolutionId() const;
    EXPORT bool solutionIdIsSet() const;
    EXPORT void unsetsolutionId();

    EXPORT void setSolutionId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    EXPORT utility::string_t getSolutionName() const;
    EXPORT bool solutionNameIsSet() const;
    EXPORT void unsetsolutionName();

    EXPORT void setSolutionName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    EXPORT bool isPersistent() const;
    EXPORT bool persistentIsSet() const;
    EXPORT void unsetpersistent();

    EXPORT void setPersistent(bool value);

    /// <summary>
    /// 
    /// </summary>
    EXPORT bool isLoaded() const;
    EXPORT bool loadedIsSet() const;
    EXPORT void unsetloaded();

    EXPORT void setLoaded(bool value);

    /// <summary>
    /// 
    /// </summary>
    EXPORT bool isRunning() const;
    EXPORT bool runningIsSet() const;
    EXPORT void unsetrunning();

    EXPORT void setRunning(bool value);

    /// <summary>
    /// 
    /// </summary>
    EXPORT utility::string_t getFps() const;
    EXPORT bool fpsIsSet() const;
    EXPORT void unsetfps();

    EXPORT void setFps(const utility::string_t& value);


protected:
    utility::string_t m_instanceId;
    bool m_instanceIdIsSet;
    utility::string_t m_displayName;
    bool m_displayNameIsSet;
    utility::string_t m_group;
    bool m_groupIsSet;
    utility::string_t m_solutionId;
    bool m_solutionIdIsSet;
    utility::string_t m_solutionName;
    bool m_solutionNameIsSet;
    bool m_persistent;
    bool m_persistentIsSet;
    bool m_loaded;
    bool m_loadedIsSet;
    bool m_running;
    bool m_runningIsSet;
    utility::string_t m_fps;
    bool m_fpsIsSet;
};


}
}
}
}
}

#endif /* CVEDIA_RT_REST_CLIENT_MODEL_InstanceRead_H_ */
