/**
 * CVEDIA-RT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@cvedia.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SecurtSetInputV1_request.h
 *
 * 
 */

#ifndef CVEDIA_RT_REST_CLIENT_MODEL_SecurtSetInputV1_request_H_
#define CVEDIA_RT_REST_CLIENT_MODEL_SecurtSetInputV1_request_H_


#include "defines.h"
#include "rt_rest_client/ModelBase.h"

#include "rt_rest_client/model/Input.h"
#include <cpprest/details/basic_types.h>

namespace cvedia {
namespace rt {
namespace rest {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class EXPORT_CLASS  SecurtSetInputV1_request
    : public ModelBase
{
public:
    EXPORT SecurtSetInputV1_request();
    EXPORT virtual ~SecurtSetInputV1_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    EXPORT void validate() override;

    EXPORT web::json::value toJson() const override;
    EXPORT bool fromJson(const web::json::value& json) override;

    EXPORT void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    EXPORT bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SecurtSetInputV1_request members

    /// <summary>
    /// 
    /// </summary>
    EXPORT std::shared_ptr<Input> getType() const;
    EXPORT bool typeIsSet() const;
    EXPORT void unsettype();

    EXPORT void setType(const std::shared_ptr<Input>& value);

    /// <summary>
    /// uri is not required for Manual mode
    /// </summary>
    EXPORT utility::string_t getUri() const;
    EXPORT bool uriIsSet() const;
    EXPORT void unseturi();

    EXPORT void setUri(const utility::string_t& value);


protected:
    std::shared_ptr<Input> m_type;
    bool m_typeIsSet;
    utility::string_t m_uri;
    bool m_uriIsSet;
};


}
}
}
}
}

#endif /* CVEDIA_RT_REST_CLIENT_MODEL_SecurtSetInputV1_request_H_ */
