/**
 * CVEDIA-RT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.2.3
 * Contact: support@cvedia.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.1.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SecurtSetAppearanceSearchV1_request.h
 *
 * 
 */

#ifndef CVEDIA_RT_REST_CLIENT_MODEL_SecurtSetAppearanceSearchV1_request_H_
#define CVEDIA_RT_REST_CLIENT_MODEL_SecurtSetAppearanceSearchV1_request_H_


#include "defines.h"
#include "rt_rest_client/ModelBase.h"

#include "rt_rest_client/model/AppearanceSearchMode.h"

namespace cvedia {
namespace rt {
namespace rest {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class EXPORT_CLASS  SecurtSetAppearanceSearchV1_request
    : public ModelBase
{
public:
    EXPORT SecurtSetAppearanceSearchV1_request();
    EXPORT virtual ~SecurtSetAppearanceSearchV1_request();

    /////////////////////////////////////////////
    /// ModelBase overrides

    EXPORT void validate() override;

    EXPORT web::json::value toJson() const override;
    EXPORT bool fromJson(const web::json::value& json) override;

    EXPORT void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    EXPORT bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SecurtSetAppearanceSearchV1_request members

    /// <summary>
    /// 
    /// </summary>
    EXPORT std::shared_ptr<AppearanceSearchMode> getMode() const;
    EXPORT bool modeIsSet() const;
    EXPORT void unsetmode();

    EXPORT void setMode(const std::shared_ptr<AppearanceSearchMode>& value);


protected:
    std::shared_ptr<AppearanceSearchMode> m_mode;
    bool m_modeIsSet;
};


}
}
}
}
}

#endif /* CVEDIA_RT_REST_CLIENT_MODEL_SecurtSetAppearanceSearchV1_request_H_ */
