/**
 * CVEDIA-RT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.2.2
 * Contact: support@cvedia.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.1.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SystemConfigEntity.h
 *
 * 
 */

#ifndef CVEDIA_RT_REST_CLIENT_MODEL_SystemConfigEntity_H_
#define CVEDIA_RT_REST_CLIENT_MODEL_SystemConfigEntity_H_


#include "defines.h"
#include "rt_rest_client/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "rt_rest_client/model/DisplayableEntity.h"
#include <vector>

namespace cvedia {
namespace rt {
namespace rest {
namespace client {
namespace model {

class DisplayableEntity;

/// <summary>
/// 
/// </summary>
class EXPORT_CLASS  SystemConfigEntity
    : public ModelBase
{
public:
    EXPORT SystemConfigEntity();
    EXPORT virtual ~SystemConfigEntity();

    /////////////////////////////////////////////
    /// ModelBase overrides

    EXPORT void validate() override;

    EXPORT web::json::value toJson() const override;
    EXPORT bool fromJson(const web::json::value& json) override;

    EXPORT void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    EXPORT bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SystemConfigEntity members

    /// <summary>
    /// 
    /// </summary>
    EXPORT utility::string_t getFieldId() const;
    EXPORT bool fieldIdIsSet() const;
    EXPORT void unsetfieldId();

    EXPORT void setFieldId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    EXPORT utility::string_t getDisplayName() const;
    EXPORT bool displayNameIsSet() const;
    EXPORT void unsetdisplayName();

    EXPORT void setDisplayName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    EXPORT utility::string_t getType() const;
    EXPORT bool typeIsSet() const;
    EXPORT void unsettype();

    EXPORT void setType(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    EXPORT utility::string_t getValue() const;
    EXPORT bool valueIsSet() const;
    EXPORT void unsetvalue();

    EXPORT void setValue(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    EXPORT utility::string_t getGroup() const;
    EXPORT bool groupIsSet() const;
    EXPORT void unsetgroup();

    EXPORT void setGroup(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    EXPORT std::vector<std::shared_ptr<DisplayableEntity>>& getAvailableValues();
    EXPORT bool availableValuesIsSet() const;
    EXPORT void unsetavailableValues();

    EXPORT void setAvailableValues(const std::vector<std::shared_ptr<DisplayableEntity>>& value);


protected:
    utility::string_t m_fieldId;
    bool m_fieldIdIsSet;
    utility::string_t m_displayName;
    bool m_displayNameIsSet;
    utility::string_t m_type;
    bool m_typeIsSet;
    utility::string_t m_value;
    bool m_valueIsSet;
    utility::string_t m_group;
    bool m_groupIsSet;
    std::vector<std::shared_ptr<DisplayableEntity>> m_availableValues;
    bool m_availableValuesIsSet;
};


}
}
}
}
}

#endif /* CVEDIA_RT_REST_CLIENT_MODEL_SystemConfigEntity_H_ */
