/**
 * CVEDIA-RT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@cvedia.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MultipartFormData.h
 *
 * This class represents a container for building application/x-multipart-formdata requests.
 */

#ifndef CVEDIA_RT_REST_CLIENT_MODEL_MultipartFormData_H_
#define CVEDIA_RT_REST_CLIENT_MODEL_MultipartFormData_H_


#include "defines.h"
#include "securt_rest_client/IHttpBody.h"
#include "securt_rest_client/HttpContent.h"

#include <cpprest/details/basic_types.h>

#include <vector>
#include <map>
#include <memory>

namespace cvedia {
namespace rt {
namespace rest {
namespace client {
namespace model {

class EXPORT_CLASS  MultipartFormData
    : public IHttpBody
{
public:
    EXPORT MultipartFormData();
    EXPORT MultipartFormData(const utility::string_t& boundary);
    EXPORT virtual ~MultipartFormData();

    EXPORT virtual void add( std::shared_ptr<HttpContent> content );
    EXPORT virtual utility::string_t getBoundary();
    EXPORT virtual std::shared_ptr<HttpContent> getContent(const utility::string_t& name) const;
    EXPORT virtual bool hasContent(const utility::string_t& name) const;
    EXPORT virtual void writeTo( std::ostream& target );

protected:
    std::vector<std::shared_ptr<HttpContent>> m_Contents;
    utility::string_t m_Boundary;
    std::map<utility::string_t, std::shared_ptr<HttpContent>> m_ContentLookup;
};

}
}
}
}
}

#endif /* CVEDIA_RT_REST_CLIENT_MODEL_MultipartFormData_H_ */
