steps:
  - script: |
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda env create --file environment-dev.yml
    displayName: Install dependencies

  - script: |
      source activate xtensor
      mkdir build
      cd build
      cmake -DXTENSOR_USE_XSIMD=ON -DDOWNLOAD_GTEST=ON $(Build.SourcesDirectory)
    displayName: Configure xtensor
    workingDirectory: $(Build.BinariesDirectory)
      
  - script: |
      source activate xtensor
      make -j2 test_xtensor_lib
    displayName: Build xtensor
    workingDirectory: $(Build.BinariesDirectory)/build
          
  - script: |
      source activate xtensor
      cd test
      ./test_xtensor_lib
    displayName: Test xtensor
    workingDirectory: $(Build.BinariesDirectory)/build/test
