/**
 * CVEDIA-RT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@cvedia.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.1.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "rt_rest_client/model/Class.h"

namespace cvedia {
namespace rt {
namespace rest {
namespace client {
namespace model {


namespace
{
using EnumUnderlyingType = utility::string_t;

Class::eClass toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("Person")))
        return Class::eClass::Class_PERSON;
    if (val == utility::conversions::to_string_t(U("Animal")))
        return Class::eClass::Class_ANIMAL;
    if (val == utility::conversions::to_string_t(U("Vehicle")))
        return Class::eClass::Class_VEHICLE;
    if (val == utility::conversions::to_string_t(U("Face")))
        return Class::eClass::Class_FACE;
    if (val == utility::conversions::to_string_t(U("Unknown")))
        return Class::eClass::Class_UNKNOWN;
    return {};
}

EnumUnderlyingType fromEnum(Class::eClass e)
{
    switch (e)
    {
    case Class::eClass::Class_PERSON:
        return U("Person");
    case Class::eClass::Class_ANIMAL:
        return U("Animal");
    case Class::eClass::Class_VEHICLE:
        return U("Vehicle");
    case Class::eClass::Class_FACE:
        return U("Face");
    case Class::eClass::Class_UNKNOWN:
        return U("Unknown");
    default:
        break;
    }
    return {};
}
}

Class::Class()
{
}

Class::~Class()
{
}

void Class::validate()
{
    // TODO: implement validation
}

web::json::value Class::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool Class::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void Class::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool Class::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

Class::eClass Class::getValue() const
{
   return m_value;
}

void Class::setValue(Class::eClass const value)
{
   m_value = value;
}


}
}
}
}
}


