/**
 * CVEDIA-RT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.2.2
 * Contact: support@cvedia.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.1.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "rt_rest_client/model/CoreGetVersionV1_200_response.h"

namespace cvedia {
namespace rt {
namespace rest {
namespace client {
namespace model {



CoreGetVersionV1_200_response::CoreGetVersionV1_200_response()
{
    m_engine = utility::conversions::to_string_t("");
    m_engineIsSet = false;
}

CoreGetVersionV1_200_response::~CoreGetVersionV1_200_response()
{
}

void CoreGetVersionV1_200_response::validate()
{
    // TODO: implement validation
}

web::json::value CoreGetVersionV1_200_response::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_engineIsSet)
    {
        val[utility::conversions::to_string_t(U("engine"))] = ModelBase::toJson(m_engine);
    }

    return val;
}

bool CoreGetVersionV1_200_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("engine"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("engine")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setEngine;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEngine);
            setEngine(refVal_setEngine);
        }
    }
    return ok;
}

void CoreGetVersionV1_200_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_engineIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("engine")), m_engine));
    }
}

bool CoreGetVersionV1_200_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("engine"))))
    {
        utility::string_t refVal_setEngine;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("engine"))), refVal_setEngine );
        setEngine(refVal_setEngine);
    }
    return ok;
}

utility::string_t CoreGetVersionV1_200_response::getEngine() const
{
    return m_engine;
}

void CoreGetVersionV1_200_response::setEngine(const utility::string_t& value)
{
    m_engine = value;
    m_engineIsSet = true;
}

bool CoreGetVersionV1_200_response::engineIsSet() const
{
    return m_engineIsSet;
}

void CoreGetVersionV1_200_response::unsetengine()
{
    m_engineIsSet = false;
}
}
}
}
}
}


