/**
 * CVEDIA-RT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.2.2
 * Contact: support@cvedia.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.1.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "rt_rest_client/model/SecurtSetAppearanceSearchV1_request.h"

namespace cvedia {
namespace rt {
namespace rest {
namespace client {
namespace model {



SecurtSetAppearanceSearchV1_request::SecurtSetAppearanceSearchV1_request()
{
    m_modeIsSet = false;
}

SecurtSetAppearanceSearchV1_request::~SecurtSetAppearanceSearchV1_request()
{
}

void SecurtSetAppearanceSearchV1_request::validate()
{
    // TODO: implement validation
}

web::json::value SecurtSetAppearanceSearchV1_request::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_modeIsSet)
    {
        val[utility::conversions::to_string_t(U("mode"))] = ModelBase::toJson(m_mode);
    }

    return val;
}

bool SecurtSetAppearanceSearchV1_request::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("mode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("mode")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AppearanceSearchMode> refVal_setMode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMode);
            setMode(refVal_setMode);
        }
    }
    return ok;
}

void SecurtSetAppearanceSearchV1_request::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_modeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("mode")), m_mode));
    }
}

bool SecurtSetAppearanceSearchV1_request::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("mode"))))
    {
        std::shared_ptr<AppearanceSearchMode> refVal_setMode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("mode"))), refVal_setMode );
        setMode(refVal_setMode);
    }
    return ok;
}

std::shared_ptr<AppearanceSearchMode> SecurtSetAppearanceSearchV1_request::getMode() const
{
    return m_mode;
}

void SecurtSetAppearanceSearchV1_request::setMode(const std::shared_ptr<AppearanceSearchMode>& value)
{
    m_mode = value;
    m_modeIsSet = true;
}

bool SecurtSetAppearanceSearchV1_request::modeIsSet() const
{
    return m_modeIsSet;
}

void SecurtSetAppearanceSearchV1_request::unsetmode()
{
    m_modeIsSet = false;
}
}
}
}
}
}


