/**
 * CVEDIA-RT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * Contact: support@cvedia.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.2.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "securt_rest_client/model/SecurtSetOutputHlsV1_200_response.h"

namespace cvedia {
namespace rt {
namespace rest {
namespace client {
namespace model {



SecurtSetOutputHlsV1_200_response::SecurtSetOutputHlsV1_200_response()
{
    m_uri = utility::conversions::to_string_t("");
    m_uriIsSet = false;
}

SecurtSetOutputHlsV1_200_response::~SecurtSetOutputHlsV1_200_response()
{
}

void SecurtSetOutputHlsV1_200_response::validate()
{
    // TODO: implement validation
}

web::json::value SecurtSetOutputHlsV1_200_response::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_uriIsSet)
    {
        val[utility::conversions::to_string_t(U("uri"))] = ModelBase::toJson(m_uri);
    }

    return val;
}

bool SecurtSetOutputHlsV1_200_response::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("uri"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("uri")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUri;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUri);
            setUri(refVal_setUri);
        }
    }
    return ok;
}

void SecurtSetOutputHlsV1_200_response::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_uriIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("uri")), m_uri));
    }
}

bool SecurtSetOutputHlsV1_200_response::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("uri"))))
    {
        utility::string_t refVal_setUri;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("uri"))), refVal_setUri );
        setUri(refVal_setUri);
    }
    return ok;
}

utility::string_t SecurtSetOutputHlsV1_200_response::getUri() const
{
    return m_uri;
}

void SecurtSetOutputHlsV1_200_response::setUri(const utility::string_t& value)
{
    m_uri = value;
    m_uriIsSet = true;
}

bool SecurtSetOutputHlsV1_200_response::uriIsSet() const
{
    return m_uriIsSet;
}

void SecurtSetOutputHlsV1_200_response::unseturi()
{
    m_uriIsSet = false;
}
}
}
}
}
}


