/**
 * CVEDIA-RT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.2.1
 * Contact: support@cvedia.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.1.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "rt_rest_client/model/SensorModality.h"

namespace cvedia {
namespace rt {
namespace rest {
namespace client {
namespace model {


namespace
{
using EnumUnderlyingType = utility::string_t;

SensorModality::eSensorModality toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("RGB")))
        return SensorModality::eSensorModality::SensorModality_RGB;
    if (val == utility::conversions::to_string_t(U("Thermal")))
        return SensorModality::eSensorModality::SensorModality_THERMAL;
    return {};
}

EnumUnderlyingType fromEnum(SensorModality::eSensorModality e)
{
    switch (e)
    {
    case SensorModality::eSensorModality::SensorModality_RGB:
        return U("RGB");
    case SensorModality::eSensorModality::SensorModality_THERMAL:
        return U("Thermal");
    default:
        break;
    }
    return {};
}
}

SensorModality::SensorModality()
{
}

SensorModality::~SensorModality()
{
}

void SensorModality::validate()
{
    // TODO: implement validation
}

web::json::value SensorModality::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool SensorModality::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void SensorModality::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool SensorModality::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

SensorModality::eSensorModality SensorModality::getValue() const
{
   return m_value;
}

void SensorModality::setValue(SensorModality::eSensorModality const value)
{
   m_value = value;
}


}
}
}
}
}


