/**
 * CVEDIA-RT
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024.2.3
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.1.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "rt_rest_client/model/Sensitivity.h"

namespace cvedia {
namespace rt {
namespace rest {
namespace client {
namespace model {


namespace
{
using EnumUnderlyingType = utility::string_t;

Sensitivity::eSensitivity toEnum(const EnumUnderlyingType& val)
{
    if (val == utility::conversions::to_string_t(U("Low")))
        return Sensitivity::eSensitivity::Sensitivity_LOW;
    if (val == utility::conversions::to_string_t(U("Medium")))
        return Sensitivity::eSensitivity::Sensitivity_MEDIUM;
    if (val == utility::conversions::to_string_t(U("High")))
        return Sensitivity::eSensitivity::Sensitivity_HIGH;
    return {};
}

EnumUnderlyingType fromEnum(Sensitivity::eSensitivity e)
{
    switch (e)
    {
    case Sensitivity::eSensitivity::Sensitivity_LOW:
        return U("Low");
    case Sensitivity::eSensitivity::Sensitivity_MEDIUM:
        return U("Medium");
    case Sensitivity::eSensitivity::Sensitivity_HIGH:
        return U("High");
    default:
        break;
    }
    return {};
}
}

Sensitivity::Sensitivity()
{
}

Sensitivity::~Sensitivity()
{
}

void Sensitivity::validate()
{
    // TODO: implement validation
}

web::json::value Sensitivity::toJson() const
{
    auto val = fromEnum(m_value);
    return web::json::value(val);
}

bool Sensitivity::fromJson(const web::json::value& val)
{
    m_value = toEnum(val.as_string());
    return true;
}

void Sensitivity::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }

    auto e = fromEnum(m_value);
    multipart->add(ModelBase::toHttpContent(namePrefix, e));
}

bool Sensitivity::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if (!namePrefix.empty() && namePrefix.back() != U('.'))
    {
        namePrefix.push_back(U('.'));
    }
    {
        EnumUnderlyingType e;
        ok = ModelBase::fromHttpContent(multipart->getContent(namePrefix), e);
        if (ok)
        {
            auto v = toEnum(e);
            setValue(v);
        }
    }
    return ok;
}

Sensitivity::eSensitivity Sensitivity::getValue() const
{
   return m_value;
}

void Sensitivity::setValue(Sensitivity::eSensitivity const value)
{
   m_value = value;
}


}
}
}
}
}


